### ISSUE TITLE
FileNotFoundError: Urgent!!!!

### ISSUE THREAD

**Issue by pravzK94** [duncster94/BIONIC-evals#8]
Hi,

I have been trying to execute the evaluations for module detection after the release update. It is been throwing the error:

(mtbenv) C:\Mtbevals>bioniceval "C:\Mtbevals\Modules_mtbscript.json"
module_detection
Traceback (most recent call last):
  File "C:\Mtbevals\mtbenv\Scripts\\bioniceval", line 5, in <module>
    main()
  File "C:\Mtbevals\BIONIC-evals\bioniceval\main.py", line 43, in main
    app()
  File "C:\Mtbevals\mtbenv\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Mtbevals\mtbenv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Mtbevals\mtbenv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Mtbevals\mtbenv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Mtbevals\mtbenv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Mtbevals\mtbenv\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Mtbevals\BIONIC-evals\bioniceval\main.py", line 28, in evaluate
    evaluate_task(task)
  File "C:\Mtbevals\BIONIC-evals\bioniceval\main.py", line 35, in evaluate_task
    module_detection_eval()
  File "C:\Mtbevals\BIONIC-evals\bioniceval\evals\module_detection.py", line 64, in module_detection_eval
    evaluations.to_csv(
  File "C:\Mtbevals\mtbenv\lib\site-packages\pandas\core\generic.py", line 3386, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Mtbevals\mtbenv\lib\site-packages\pandas\io\formats\format.py", line 1083, in to_csv
    csv_formatter.save()
  File "C:\Mtbevals\mtbenv\lib\site-packages\pandas\io\formats\csvs.py", line 228, in save
    with get_handle(
  File "C:\Mtbevals\mtbenv\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'bioniceval\\results\\Modules_mtbscript_module_detection.tsv'

I guess, it is because of no mention of results directory in the config .json file. I am also, attaching the config file here. Please, help out in this regard, it is very urgent.

Thanks and regards
Praveena K
[Module_mtdscript.txt](https://github.com/duncster94/BIONIC-evals/files/9278578/Module_mtdscript.txt)

**Comment by duncster94** [comment]
Hi, can you try running the eval from the directory containing `bioniceval`? Looks like you should `cd` into your `Scripts` directory and run `bioniceval "C:\Mtbevals\Modules_mtbscript.json"` like before.

I would recommend testing that this works before running a full size evaluation. You can reduce the `"samples"` key in the config to `1` and `"thresholds"` to `1`. You can also reduce the number of networks you're evaluating on. This shouldn't take long to complete.

Let me know if that fixes the problem and I'll update the README and/or push a new version.

**Comment by pravzK94** [comment]
Hi,
I have attempted to test with above suggestions and still comes up the same error:

(mtbenv) C:\Mtbevals\mtbenv\Scripts>bioniceval C:\Mtbevals\Module_mtdscript.txt
module_detection
Traceback (most recent call last):
  File "C:\Mtbevals\mtbenv\Scripts\\bioniceval", line 5, in <module>
    main()
  File "C:\Mtbevals\BIONIC-evals\bioniceval\main.py", line 43, in main
    app()
  File "C:\Mtbevals\mtbenv\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Mtbevals\mtbenv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Mtbevals\mtbenv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Mtbevals\mtbenv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Mtbevals\mtbenv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Mtbevals\mtbenv\lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Mtbevals\BIONIC-evals\bioniceval\main.py", line 28, in evaluate
    evaluate_task(task)
  File "C:\Mtbevals\BIONIC-evals\bioniceval\main.py", line 35, in evaluate_task
    module_detection_eval()
  File "C:\Mtbevals\BIONIC-evals\bioniceval\evals\module_detection.py", line 64, in module_detection_eval
    evaluations.to_csv(
  File "C:\Mtbevals\mtbenv\lib\site-packages\pandas\core\generic.py", line 3386, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Mtbevals\mtbenv\lib\site-packages\pandas\io\formats\format.py", line 1083, in to_csv
    csv_formatter.save()
  File "C:\Mtbevals\mtbenv\lib\site-packages\pandas\io\formats\csvs.py", line 228, in save
    with get_handle(
  File "C:\Mtbevals\mtbenv\lib\site-packages\pandas\io\common.py", line 642, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'bioniceval\\results\\Module_mtdscript_module_detection.tsv'

I am currently running this on a windows platform and request you to help me out encounter the same. 

Thank you so much
Praveena K

**Comment by duncster94** [comment]
You can try replacing `State.result_path / Path(f"{State.config_name}_module_detection.tsv")` in [this](https://github.com/duncster94/BIONIC-evals/blob/45d5b7f4f4713d9312af4ad7c56ac98338b466a3/bioniceval/evals/module_detection.py#L65) line with an absolute path on your system. It's a temporary hack until I can take a closer look. Something like `Path("C:\\Mtbevals\\mtbenv\\Scripts\\module_detection.tsv")` should work.

Let me know if you still encounter problems.

**Comment by pravzK94** [comment]
Hi again,

This time modifying the python script with given suggestion has worked. Along with module detection.py file, a similar replacement was made in the plotting.py. 

With an experience of using BIONIC as well, I suggest that an inclusion of key for results in the config .json file will be feasible for efficient usage (similar to 'out_names' key in BIONIC keys). 

Thanks and regards
Praveena K
